// Regenerates test/vectors/credential.json from fixed inputs. Run with:
//   node packages/private-credential-core/scripts/gen-vectors.ts
// These are GOLDEN vectors: the Phase 2 Compact circuit must reproduce every output hex.
// Re-run only when an encoding rule legitimately changes (and document why).

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { toHex, fromHex } from "../src/bytes.ts";
import { xrplAddressToBytes32 } from "../src/account-id.ts";
import { POLICY_ID32 } from "../src/hash.ts";
import { deriveHolderKey, credentialLeaf, requestCommitment, nullifier, type PrivateCredential } from "../src/credential.ts";

const fill = (b: number) => new Uint8Array(32).fill(b);

const inputs = {
  holderSecretHex: toHex(fill(0x01)),
  credentialIdHex: toHex(fill(0x02)),
  issuerRandomnessHex: toHex(fill(0x03)),
  requestNonceHex: toHex(fill(0x04)),
  schemaVersion: 1,
  birthYear: 2000,
  jurisdictionCode: "CA",
  validUntilPolicyEpoch: 1,
  xrplAddress: "rL6R6fce1bfTxgj1S7mxQ2f4EBonv6wbyB",
  policyEpoch: 1,
};

const holderSecret = fromHex(inputs.holderSecretHex);
const credentialId = fromHex(inputs.credentialIdHex);
const issuerRandomness = fromHex(inputs.issuerRandomnessHex);
const requestNonce = fromHex(inputs.requestNonceHex);
const holderKey = deriveHolderKey(holderSecret);
const accountId32 = xrplAddressToBytes32(inputs.xrplAddress);

const cred: PrivateCredential = {
  schemaVersion: inputs.schemaVersion,
  credentialId,
  holderKey,
  birthYear: inputs.birthYear,
  jurisdictionCode: inputs.jurisdictionCode,
  validUntilPolicyEpoch: inputs.validUntilPolicyEpoch,
  issuerRandomness,
};

const expected = {
  policyId32Hex: toHex(POLICY_ID32),
  accountId32Hex: toHex(accountId32),
  holderKeyHex: toHex(holderKey),
  credentialLeafHex: toHex(credentialLeaf(cred)),
  requestCommitmentHex: toHex(requestCommitment({ xrplAccountId32: accountId32, requestNonce, policyEpoch: inputs.policyEpoch })),
  nullifierHex: toHex(nullifier({ holderSecret, credentialId })),
};

const out = {
  _comment:
    "GOLDEN cross-language vectors. The Phase 2 Compact circuit must reproduce every 'expected' hex from the same inputs. Generated by scripts/gen-vectors.ts using @midnight-ntwrk/compact-runtime persistentHash/persistentCommit.",
  runtime: "@midnight-ntwrk/compact-runtime@0.16.0",
  inputs,
  expected,
};

const path = fileURLToPath(new URL("../test/vectors/credential.json", import.meta.url));
writeFileSync(path, JSON.stringify(out, null, 2) + "\n");
console.log("wrote", path);
console.log(JSON.stringify(expected, null, 2));
